#!/bin/bash
set -eu

printf "\n\nEdit ./Ellies/Step02.elm and see the changes in the browser\n\n"
npx elm-go Ellies/Step02.elm --pushstate --hot --start-page=ellie-tests.html --dir=docs -- --output=docs/elm.js --debug
